global:
    scrape_interval: 15s
    external_labels:
        monitor: 'cadvisor-monitor'

scrape_configs:
    - job_name: 'cadvisor-exporter'
      static_configs:
          - targets: ['211.183.3.102:8080', '211.183.3.103:8080']

    - job_name: 'node-exporter'
      static_configs:
          - targets: ['211.183.3.102:9100', '211.183.3.103:9100']
