version: '3.5'
services:

  dbcluster:
    image: toughiq/mariadb-cluster
    networks:
      - dbnet
    ports:
      - 3306:3306
    environment:
      - DB_SERVICE_NAME=dbcluster
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mydbuser
      - MYSQL_PASSWORD=test123
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          

  dblb:
    image: toughiq/maxscale
    networks:
      - dbnet
    ports:
      - 33061:3306
    environment:
      - DB_SERVICE_NAME=dbcluster
      - ENABLE_ROOT_USER=1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.manager == true

volumes:
  db:
    driver: local

networks:
  dbnet:
    external: true
